# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appwork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for appwork
  pod 'Firebase/Core'

  target 'appworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
